openapi: '3.0.2'
info:
  title: Engrada Api
  version: '1.0'
servers:
  - url: http://127.0.0.1:8000/api/app/
paths:
  /account/register:
    post:
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:          # <!--- form field name
                  type: string
                first_name:    # <!--- form field name
                  type: string
              required:
                - name
                - email
      responses:
        '200':
          description: Successfuly Register
  /account/login:
      post:
        requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  name:          # <!--- form field name
                    type: string
                  password:    # <!--- form field name
                    type: string
                required:
                  - name
                  - password
        responses:
          '200':
            description: Successfuly Logined